/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author Administrador
 */
public class ProduktuaAukeratu extends javax.swing.JFrame {

    /**
     * Creates new form ProduktuaAukeratu
     */
    public ProduktuaAukeratu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogEzabatuKonfirm = new javax.swing.JDialog();
        jTabbedPaneProd = new javax.swing.JTabbedPane();
        jPanelJerts = new javax.swing.JPanel();
        jPanelJertsKud = new javax.swing.JPanel();
        jTextFieldBilatu2 = new javax.swing.JTextField();
        jLabelJertsKud2 = new javax.swing.JLabel();
        bilatuLabel4 = new javax.swing.JLabel();
        jPanelJertsGorp = new javax.swing.JPanel();
        jPanelJertsInfo = new javax.swing.JPanel();
        jLabelMarka = new javax.swing.JLabel();
        jLabelKolorea = new javax.swing.JLabel();
        jLabelSexua = new javax.swing.JLabel();
        jLabelJaioData = new javax.swing.JLabel();
        jLabelTaila = new javax.swing.JLabel();
        jTextFieldMarka = new javax.swing.JTextField();
        jTextFieldKolorea = new javax.swing.JTextField();
        jTextFieldStock = new javax.swing.JTextField();
        jLabelPrezioa = new javax.swing.JLabel();
        jTextFieldPrezioa = new javax.swing.JTextField();
        jLabelKodJerts = new javax.swing.JLabel();
        jTextFieldKodeJerts = new javax.swing.JTextField();
        jComboBoxTaila = new javax.swing.JComboBox<>();
        jComboBoxSexua = new javax.swing.JComboBox<>();
        jPanelJertsInfoTaula = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableJertsInfo = new javax.swing.JTable();
        jPanelJertsBotoiak = new javax.swing.JPanel();
        jButtonGehituJerts = new javax.swing.JButton();
        jButtonAldatuJerts = new javax.swing.JButton();
        jButtonEzabatuJerts = new javax.swing.JButton();
        jPanelKami = new javax.swing.JPanel();
        jPanelKamiKud = new javax.swing.JPanel();
        jTextFieldBilatu3 = new javax.swing.JTextField();
        jLabelKamiKud = new javax.swing.JLabel();
        bilatuLabel5 = new javax.swing.JLabel();
        jPanelKamiGorp = new javax.swing.JPanel();
        jPanelKamiInfo = new javax.swing.JPanel();
        jLabelMarka1 = new javax.swing.JLabel();
        jLabelKolorea1 = new javax.swing.JLabel();
        jLabelSexua1 = new javax.swing.JLabel();
        jLabelJaioData1 = new javax.swing.JLabel();
        jLabelTaila1 = new javax.swing.JLabel();
        jTextFieldMarka1 = new javax.swing.JTextField();
        jTextFieldKolorea1 = new javax.swing.JTextField();
        jTextFieldStock1 = new javax.swing.JTextField();
        jLabelPrezioa1 = new javax.swing.JLabel();
        jTextFieldPrezioa1 = new javax.swing.JTextField();
        jLabelKodJerts1 = new javax.swing.JLabel();
        jTextFieldKodeJerts1 = new javax.swing.JTextField();
        jComboBoxTaila1 = new javax.swing.JComboBox<>();
        jComboBoxSexua1 = new javax.swing.JComboBox<>();
        jLabelSasoia = new javax.swing.JLabel();
        jComboBoxSasoia = new javax.swing.JComboBox<>();
        jPanelKamiInfoTaula = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableKamiInfo = new javax.swing.JTable();
        jPanelPrakBotoiak1 = new javax.swing.JPanel();
        jButtonGehituKami = new javax.swing.JButton();
        jButtonAldatuKami = new javax.swing.JButton();
        jButtonEzabatuKami = new javax.swing.JButton();
        jPanelPrak = new javax.swing.JPanel();
        jPanelPrakKud = new javax.swing.JPanel();
        jTextFieldBilatu5 = new javax.swing.JTextField();
        jLabelPrakKud1 = new javax.swing.JLabel();
        bilatuLabel7 = new javax.swing.JLabel();
        jPanelPrakGorp = new javax.swing.JPanel();
        jPanelPrakInfo = new javax.swing.JPanel();
        jLabelMarka2 = new javax.swing.JLabel();
        jLabelKolorea2 = new javax.swing.JLabel();
        jLabelSexua2 = new javax.swing.JLabel();
        jLabelJaioData2 = new javax.swing.JLabel();
        jLabelTaila2 = new javax.swing.JLabel();
        jTextFieldMarka2 = new javax.swing.JTextField();
        jTextFieldKolorea2 = new javax.swing.JTextField();
        jTextFieldStock2 = new javax.swing.JTextField();
        jLabelPrezioa2 = new javax.swing.JLabel();
        jTextFieldPrezioa2 = new javax.swing.JTextField();
        jLabelKodJerts2 = new javax.swing.JLabel();
        jTextFieldKodeJerts2 = new javax.swing.JTextField();
        jComboBoxTaila2 = new javax.swing.JComboBox<>();
        jComboBoxSexua2 = new javax.swing.JComboBox<>();
        jLabelSasoia1 = new javax.swing.JLabel();
        jComboBoxSasoia1 = new javax.swing.JComboBox<>();
        jLabelLuzeera = new javax.swing.JLabel();
        jTextFieldLuzeera = new javax.swing.JTextField();
        jLabelMota = new javax.swing.JLabel();
        jComboBoxMota = new javax.swing.JComboBox<>();
        jPanelPrakInfoTaula = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTablePrakInfo = new javax.swing.JTable();
        jPanelPrakBotoiak = new javax.swing.JPanel();
        jButtonGehituPrak = new javax.swing.JButton();
        jButtonAldatuPrak = new javax.swing.JButton();
        jButtonEzabatuPrak = new javax.swing.JButton();
        jButtonIrten = new javax.swing.JButton();

        javax.swing.GroupLayout jDialogEzabatuKonfirmLayout = new javax.swing.GroupLayout(jDialogEzabatuKonfirm.getContentPane());
        jDialogEzabatuKonfirm.getContentPane().setLayout(jDialogEzabatuKonfirmLayout);
        jDialogEzabatuKonfirmLayout.setHorizontalGroup(
            jDialogEzabatuKonfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialogEzabatuKonfirmLayout.setVerticalGroup(
            jDialogEzabatuKonfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPaneProd.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPaneProd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanelJerts.setPreferredSize(new java.awt.Dimension(1049, 665));

        jLabelJertsKud2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelJertsKud2.setText("JERTSEAK KUDEATU");

        bilatuLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/argazkiak/bilaketaLupa.png"))); // NOI18N

        javax.swing.GroupLayout jPanelJertsKudLayout = new javax.swing.GroupLayout(jPanelJertsKud);
        jPanelJertsKud.setLayout(jPanelJertsKudLayout);
        jPanelJertsKudLayout.setHorizontalGroup(
            jPanelJertsKudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJertsKudLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelJertsKud2, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bilatuLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldBilatu2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanelJertsKudLayout.setVerticalGroup(
            jPanelJertsKudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJertsKudLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextFieldBilatu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJertsKudLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelJertsKudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bilatuLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJertsKudLayout.createSequentialGroup()
                        .addComponent(jLabelJertsKud2)
                        .addContainerGap())))
        );

        jLabelMarka.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelMarka.setText("Marka:");

        jLabelKolorea.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelKolorea.setText("Kolorea:");

        jLabelSexua.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelSexua.setText("Sexua:");

        jLabelJaioData.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelJaioData.setText("Stock-ean:");

        jLabelTaila.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelTaila.setText("Taila:");

        jLabelPrezioa.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelPrezioa.setText("Prezioa:");

        jLabelKodJerts.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelKodJerts.setText("Kodea:");

        jComboBoxTaila.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxSexua.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelJertsInfoLayout = new javax.swing.GroupLayout(jPanelJertsInfo);
        jPanelJertsInfo.setLayout(jPanelJertsInfoLayout);
        jPanelJertsInfoLayout.setHorizontalGroup(
            jPanelJertsInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJertsInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelJertsInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelJertsInfoLayout.createSequentialGroup()
                        .addComponent(jLabelMarka)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldMarka, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelJertsInfoLayout.createSequentialGroup()
                        .addComponent(jLabelKolorea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jTextFieldKolorea, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelJertsInfoLayout.createSequentialGroup()
                        .addComponent(jLabelPrezioa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPrezioa, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelJertsInfoLayout.createSequentialGroup()
                        .addComponent(jLabelKodJerts)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldKodeJerts, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJertsInfoLayout.createSequentialGroup()
                        .addGroup(jPanelJertsInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelJaioData)
                            .addComponent(jLabelTaila)
                            .addComponent(jLabelSexua))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelJertsInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldStock, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(jComboBoxTaila, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxSexua, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanelJertsInfoLayout.setVerticalGroup(
            jPanelJertsInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJertsInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelJertsInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKodJerts)
                    .addComponent(jTextFieldKodeJerts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelJertsInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMarka)
                    .addComponent(jTextFieldMarka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelJertsInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrezioa)
                    .addComponent(jTextFieldPrezioa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelJertsInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKolorea)
                    .addComponent(jTextFieldKolorea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelJertsInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSexua)
                    .addComponent(jComboBoxSexua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelJertsInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJaioData)
                    .addComponent(jTextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelJertsInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTaila)
                    .addComponent(jComboBoxTaila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTableJertsInfo.setAutoCreateRowSorter(true);
        jTableJertsInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableJertsInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableJertsInfo.setToolTipText("");
        jTableJertsInfo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableJertsInfo.setAutoscrolls(false);
        jScrollPane3.setViewportView(jTableJertsInfo);

        javax.swing.GroupLayout jPanelJertsInfoTaulaLayout = new javax.swing.GroupLayout(jPanelJertsInfoTaula);
        jPanelJertsInfoTaula.setLayout(jPanelJertsInfoTaulaLayout);
        jPanelJertsInfoTaulaLayout.setHorizontalGroup(
            jPanelJertsInfoTaulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJertsInfoTaulaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelJertsInfoTaulaLayout.setVerticalGroup(
            jPanelJertsInfoTaulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJertsInfoTaulaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelJertsGorpLayout = new javax.swing.GroupLayout(jPanelJertsGorp);
        jPanelJertsGorp.setLayout(jPanelJertsGorpLayout);
        jPanelJertsGorpLayout.setHorizontalGroup(
            jPanelJertsGorpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJertsGorpLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanelJertsInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelJertsInfoTaula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelJertsGorpLayout.setVerticalGroup(
            jPanelJertsGorpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJertsGorpLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanelJertsGorpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelJertsGorpLayout.createSequentialGroup()
                        .addComponent(jPanelJertsInfoTaula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelJertsInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jButtonGehituJerts.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButtonGehituJerts.setText("Gehitu");

        jButtonAldatuJerts.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButtonAldatuJerts.setText("Aldatu");

        jButtonEzabatuJerts.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButtonEzabatuJerts.setText("Ezabatu");

        javax.swing.GroupLayout jPanelJertsBotoiakLayout = new javax.swing.GroupLayout(jPanelJertsBotoiak);
        jPanelJertsBotoiak.setLayout(jPanelJertsBotoiakLayout);
        jPanelJertsBotoiakLayout.setHorizontalGroup(
            jPanelJertsBotoiakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJertsBotoiakLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButtonEzabatuJerts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAldatuJerts)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGehituJerts)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelJertsBotoiakLayout.setVerticalGroup(
            jPanelJertsBotoiakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJertsBotoiakLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanelJertsBotoiakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEzabatuJerts)
                    .addComponent(jButtonAldatuJerts)
                    .addComponent(jButtonGehituJerts))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelJertsLayout = new javax.swing.GroupLayout(jPanelJerts);
        jPanelJerts.setLayout(jPanelJertsLayout);
        jPanelJertsLayout.setHorizontalGroup(
            jPanelJertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJertsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelJertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelJertsLayout.createSequentialGroup()
                        .addGroup(jPanelJertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelJertsGorp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelJertsKud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanelJertsBotoiak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelJertsLayout.setVerticalGroup(
            jPanelJertsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJertsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelJertsKud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelJertsGorp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelJertsBotoiak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jTabbedPaneProd.addTab("Jertsea", jPanelJerts);

        jLabelKamiKud.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelKamiKud.setText("KAMISETAK KUDEATU");

        bilatuLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/argazkiak/bilaketaLupa.png"))); // NOI18N

        javax.swing.GroupLayout jPanelKamiKudLayout = new javax.swing.GroupLayout(jPanelKamiKud);
        jPanelKamiKud.setLayout(jPanelKamiKudLayout);
        jPanelKamiKudLayout.setHorizontalGroup(
            jPanelKamiKudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelKamiKudLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelKamiKud, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bilatuLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldBilatu3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanelKamiKudLayout.setVerticalGroup(
            jPanelKamiKudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelKamiKudLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextFieldBilatu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelKamiKudLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelKamiKudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bilatuLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelKamiKudLayout.createSequentialGroup()
                        .addComponent(jLabelKamiKud)
                        .addContainerGap())))
        );

        jLabelMarka1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelMarka1.setText("Marka:");

        jLabelKolorea1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelKolorea1.setText("Kolorea:");

        jLabelSexua1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelSexua1.setText("Sexua:");

        jLabelJaioData1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelJaioData1.setText("Stock-ean:");

        jLabelTaila1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelTaila1.setText("Taila:");

        jLabelPrezioa1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelPrezioa1.setText("Prezioa:");

        jLabelKodJerts1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelKodJerts1.setText("Kodea:");

        jComboBoxTaila1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxSexua1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelSasoia.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelSasoia.setText("Sasoia:");

        jComboBoxSasoia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelKamiInfoLayout = new javax.swing.GroupLayout(jPanelKamiInfo);
        jPanelKamiInfo.setLayout(jPanelKamiInfoLayout);
        jPanelKamiInfoLayout.setHorizontalGroup(
            jPanelKamiInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKamiInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelKamiInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelKamiInfoLayout.createSequentialGroup()
                        .addComponent(jLabelMarka1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldMarka1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelKamiInfoLayout.createSequentialGroup()
                        .addComponent(jLabelKolorea1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jTextFieldKolorea1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelKamiInfoLayout.createSequentialGroup()
                        .addComponent(jLabelPrezioa1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPrezioa1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelKamiInfoLayout.createSequentialGroup()
                        .addComponent(jLabelKodJerts1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldKodeJerts1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelKamiInfoLayout.createSequentialGroup()
                        .addGroup(jPanelKamiInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelJaioData1)
                            .addComponent(jLabelTaila1)
                            .addComponent(jLabelSexua1)
                            .addComponent(jLabelSasoia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelKamiInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxSasoia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldStock1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(jComboBoxTaila1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxSexua1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanelKamiInfoLayout.setVerticalGroup(
            jPanelKamiInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelKamiInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelKamiInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKodJerts1)
                    .addComponent(jTextFieldKodeJerts1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelKamiInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMarka1)
                    .addComponent(jTextFieldMarka1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelKamiInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrezioa1)
                    .addComponent(jTextFieldPrezioa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelKamiInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKolorea1)
                    .addComponent(jTextFieldKolorea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelKamiInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSexua1)
                    .addComponent(jComboBoxSexua1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelKamiInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJaioData1)
                    .addComponent(jTextFieldStock1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelKamiInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTaila1)
                    .addComponent(jComboBoxTaila1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelKamiInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSasoia)
                    .addComponent(jComboBoxSasoia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6))
        );

        jTableKamiInfo.setAutoCreateRowSorter(true);
        jTableKamiInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTableKamiInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableKamiInfo.setToolTipText("");
        jTableKamiInfo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableKamiInfo.setAutoscrolls(false);
        jScrollPane4.setViewportView(jTableKamiInfo);

        javax.swing.GroupLayout jPanelKamiInfoTaulaLayout = new javax.swing.GroupLayout(jPanelKamiInfoTaula);
        jPanelKamiInfoTaula.setLayout(jPanelKamiInfoTaulaLayout);
        jPanelKamiInfoTaulaLayout.setHorizontalGroup(
            jPanelKamiInfoTaulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelKamiInfoTaulaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelKamiInfoTaulaLayout.setVerticalGroup(
            jPanelKamiInfoTaulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKamiInfoTaulaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelKamiGorpLayout = new javax.swing.GroupLayout(jPanelKamiGorp);
        jPanelKamiGorp.setLayout(jPanelKamiGorpLayout);
        jPanelKamiGorpLayout.setHorizontalGroup(
            jPanelKamiGorpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKamiGorpLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanelKamiInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelKamiInfoTaula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelKamiGorpLayout.setVerticalGroup(
            jPanelKamiGorpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKamiGorpLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanelKamiGorpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelKamiInfoTaula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelKamiInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonGehituKami.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButtonGehituKami.setText("Gehitu");

        jButtonAldatuKami.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButtonAldatuKami.setText("Aldatu");

        jButtonEzabatuKami.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButtonEzabatuKami.setText("Ezabatu");

        javax.swing.GroupLayout jPanelPrakBotoiak1Layout = new javax.swing.GroupLayout(jPanelPrakBotoiak1);
        jPanelPrakBotoiak1.setLayout(jPanelPrakBotoiak1Layout);
        jPanelPrakBotoiak1Layout.setHorizontalGroup(
            jPanelPrakBotoiak1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrakBotoiak1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButtonEzabatuKami)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAldatuKami)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGehituKami)
                .addContainerGap(720, Short.MAX_VALUE))
        );
        jPanelPrakBotoiak1Layout.setVerticalGroup(
            jPanelPrakBotoiak1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrakBotoiak1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPrakBotoiak1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEzabatuKami)
                    .addComponent(jButtonAldatuKami)
                    .addComponent(jButtonGehituKami))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelKamiLayout = new javax.swing.GroupLayout(jPanelKami);
        jPanelKami.setLayout(jPanelKamiLayout);
        jPanelKamiLayout.setHorizontalGroup(
            jPanelKamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKamiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelKamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelKamiKud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelKamiGorp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPrakBotoiak1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelKamiLayout.setVerticalGroup(
            jPanelKamiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelKamiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelKamiKud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelKamiGorp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPrakBotoiak1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTabbedPaneProd.addTab("Kamiseta", jPanelKami);

        jPanelPrak.setPreferredSize(new java.awt.Dimension(1049, 576));

        jLabelPrakKud1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelPrakKud1.setText("PRAKAK KUDEATU");

        bilatuLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/argazkiak/bilaketaLupa.png"))); // NOI18N

        javax.swing.GroupLayout jPanelPrakKudLayout = new javax.swing.GroupLayout(jPanelPrakKud);
        jPanelPrakKud.setLayout(jPanelPrakKudLayout);
        jPanelPrakKudLayout.setHorizontalGroup(
            jPanelPrakKudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrakKudLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPrakKud1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bilatuLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldBilatu5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanelPrakKudLayout.setVerticalGroup(
            jPanelPrakKudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrakKudLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTextFieldBilatu5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrakKudLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPrakKudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bilatuLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrakKudLayout.createSequentialGroup()
                        .addComponent(jLabelPrakKud1)
                        .addContainerGap())))
        );

        jLabelMarka2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelMarka2.setText("Marka:");

        jLabelKolorea2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelKolorea2.setText("Kolorea:");

        jLabelSexua2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelSexua2.setText("Sexua:");

        jLabelJaioData2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelJaioData2.setText("Stock-ean:");

        jLabelTaila2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelTaila2.setText("Taila:");

        jLabelPrezioa2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelPrezioa2.setText("Prezioa:");

        jLabelKodJerts2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelKodJerts2.setText("Kodea:");

        jComboBoxTaila2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jComboBoxSexua2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelSasoia1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelSasoia1.setText("Sasoia:");

        jComboBoxSasoia1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelLuzeera.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelLuzeera.setText("Luzeera:");

        jLabelMota.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabelMota.setText("Mota:");

        jComboBoxMota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelPrakInfoLayout = new javax.swing.GroupLayout(jPanelPrakInfo);
        jPanelPrakInfo.setLayout(jPanelPrakInfoLayout);
        jPanelPrakInfoLayout.setHorizontalGroup(
            jPanelPrakInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrakInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrakInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPrakInfoLayout.createSequentialGroup()
                        .addComponent(jLabelMarka2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldMarka2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPrakInfoLayout.createSequentialGroup()
                        .addComponent(jLabelKolorea2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jTextFieldKolorea2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPrakInfoLayout.createSequentialGroup()
                        .addComponent(jLabelPrezioa2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPrezioa2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPrakInfoLayout.createSequentialGroup()
                        .addComponent(jLabelKodJerts2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldKodeJerts2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrakInfoLayout.createSequentialGroup()
                        .addGroup(jPanelPrakInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelJaioData2)
                            .addComponent(jLabelTaila2)
                            .addComponent(jLabelSexua2)
                            .addComponent(jLabelSasoia1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelPrakInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBoxSasoia1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldStock2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                            .addComponent(jComboBoxTaila2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxSexua2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelPrakInfoLayout.createSequentialGroup()
                        .addGroup(jPanelPrakInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelLuzeera)
                            .addComponent(jLabelMota))
                        .addGap(22, 22, 22)
                        .addGroup(jPanelPrakInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldLuzeera)
                            .addComponent(jComboBoxMota, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        jPanelPrakInfoLayout.setVerticalGroup(
            jPanelPrakInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrakInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPrakInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKodJerts2)
                    .addComponent(jTextFieldKodeJerts2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrakInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMarka2)
                    .addComponent(jTextFieldMarka2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrakInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrezioa2)
                    .addComponent(jTextFieldPrezioa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrakInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelKolorea2)
                    .addComponent(jTextFieldKolorea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrakInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSexua2)
                    .addComponent(jComboBoxSexua2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrakInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJaioData2)
                    .addComponent(jTextFieldStock2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrakInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTaila2)
                    .addComponent(jComboBoxTaila2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrakInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSasoia1)
                    .addComponent(jComboBoxSasoia1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrakInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLuzeera)
                    .addComponent(jTextFieldLuzeera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPrakInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMota)
                    .addComponent(jComboBoxMota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTablePrakInfo.setAutoCreateRowSorter(true);
        jTablePrakInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTablePrakInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTablePrakInfo.setToolTipText("");
        jTablePrakInfo.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTablePrakInfo.setAutoscrolls(false);
        jScrollPane5.setViewportView(jTablePrakInfo);

        javax.swing.GroupLayout jPanelPrakInfoTaulaLayout = new javax.swing.GroupLayout(jPanelPrakInfoTaula);
        jPanelPrakInfoTaula.setLayout(jPanelPrakInfoTaulaLayout);
        jPanelPrakInfoTaulaLayout.setHorizontalGroup(
            jPanelPrakInfoTaulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrakInfoTaulaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelPrakInfoTaulaLayout.setVerticalGroup(
            jPanelPrakInfoTaulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrakInfoTaulaLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelPrakGorpLayout = new javax.swing.GroupLayout(jPanelPrakGorp);
        jPanelPrakGorp.setLayout(jPanelPrakGorpLayout);
        jPanelPrakGorpLayout.setHorizontalGroup(
            jPanelPrakGorpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrakGorpLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanelPrakInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelPrakInfoTaula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelPrakGorpLayout.setVerticalGroup(
            jPanelPrakGorpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrakGorpLayout.createSequentialGroup()
                .addGroup(jPanelPrakGorpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPrakInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelPrakInfoTaula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButtonGehituPrak.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButtonGehituPrak.setText("Gehitu");

        jButtonAldatuPrak.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButtonAldatuPrak.setText("Aldatu");

        jButtonEzabatuPrak.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButtonEzabatuPrak.setText("Ezabatu");

        javax.swing.GroupLayout jPanelPrakBotoiakLayout = new javax.swing.GroupLayout(jPanelPrakBotoiak);
        jPanelPrakBotoiak.setLayout(jPanelPrakBotoiakLayout);
        jPanelPrakBotoiakLayout.setHorizontalGroup(
            jPanelPrakBotoiakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrakBotoiakLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jButtonEzabatuPrak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAldatuPrak)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGehituPrak)
                .addContainerGap(720, Short.MAX_VALUE))
        );
        jPanelPrakBotoiakLayout.setVerticalGroup(
            jPanelPrakBotoiakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrakBotoiakLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelPrakBotoiakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEzabatuPrak)
                    .addComponent(jButtonAldatuPrak)
                    .addComponent(jButtonGehituPrak))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelPrakLayout = new javax.swing.GroupLayout(jPanelPrak);
        jPanelPrak.setLayout(jPanelPrakLayout);
        jPanelPrakLayout.setHorizontalGroup(
            jPanelPrakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrakLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPrakKud, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPrakGorp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelPrakBotoiak, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelPrakLayout.setVerticalGroup(
            jPanelPrakLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrakLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrakKud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelPrakGorp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelPrakBotoiak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPaneProd.addTab("Praka", jPanelPrak);

        jButtonIrten.setBackground(new java.awt.Color(51, 0, 0));
        jButtonIrten.setFont(new java.awt.Font("Calibri Light", 1, 14)); // NOI18N
        jButtonIrten.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIrten.setText("Irten");
        jButtonIrten.setBorderPainted(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPaneProd)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonIrten)
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(jTabbedPaneProd, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonIrten)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProduktuaAukeratu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProduktuaAukeratu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProduktuaAukeratu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProduktuaAukeratu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProduktuaAukeratu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bilatuLabel4;
    private javax.swing.JLabel bilatuLabel5;
    private javax.swing.JLabel bilatuLabel7;
    public javax.swing.JButton jButtonAldatuJerts;
    public javax.swing.JButton jButtonAldatuKami;
    public javax.swing.JButton jButtonAldatuPrak;
    public javax.swing.JButton jButtonEzabatuJerts;
    public javax.swing.JButton jButtonEzabatuKami;
    public javax.swing.JButton jButtonEzabatuPrak;
    public javax.swing.JButton jButtonGehituJerts;
    public javax.swing.JButton jButtonGehituKami;
    public javax.swing.JButton jButtonGehituPrak;
    public javax.swing.JButton jButtonIrten;
    public javax.swing.JComboBox<String> jComboBoxMota;
    public javax.swing.JComboBox<String> jComboBoxSasoia;
    public javax.swing.JComboBox<String> jComboBoxSasoia1;
    public javax.swing.JComboBox<String> jComboBoxSexua;
    public javax.swing.JComboBox<String> jComboBoxSexua1;
    public javax.swing.JComboBox<String> jComboBoxSexua2;
    public javax.swing.JComboBox<String> jComboBoxTaila;
    public javax.swing.JComboBox<String> jComboBoxTaila1;
    public javax.swing.JComboBox<String> jComboBoxTaila2;
    public javax.swing.JDialog jDialogEzabatuKonfirm;
    private javax.swing.JLabel jLabelJaioData;
    private javax.swing.JLabel jLabelJaioData1;
    private javax.swing.JLabel jLabelJaioData2;
    private javax.swing.JLabel jLabelJertsKud2;
    private javax.swing.JLabel jLabelKamiKud;
    private javax.swing.JLabel jLabelKodJerts;
    private javax.swing.JLabel jLabelKodJerts1;
    private javax.swing.JLabel jLabelKodJerts2;
    private javax.swing.JLabel jLabelKolorea;
    private javax.swing.JLabel jLabelKolorea1;
    private javax.swing.JLabel jLabelKolorea2;
    private javax.swing.JLabel jLabelLuzeera;
    private javax.swing.JLabel jLabelMarka;
    private javax.swing.JLabel jLabelMarka1;
    private javax.swing.JLabel jLabelMarka2;
    private javax.swing.JLabel jLabelMota;
    private javax.swing.JLabel jLabelPrakKud1;
    private javax.swing.JLabel jLabelPrezioa;
    private javax.swing.JLabel jLabelPrezioa1;
    private javax.swing.JLabel jLabelPrezioa2;
    private javax.swing.JLabel jLabelSasoia;
    private javax.swing.JLabel jLabelSasoia1;
    private javax.swing.JLabel jLabelSexua;
    private javax.swing.JLabel jLabelSexua1;
    private javax.swing.JLabel jLabelSexua2;
    private javax.swing.JLabel jLabelTaila;
    private javax.swing.JLabel jLabelTaila1;
    private javax.swing.JLabel jLabelTaila2;
    public javax.swing.JPanel jPanelJerts;
    private javax.swing.JPanel jPanelJertsBotoiak;
    private javax.swing.JPanel jPanelJertsGorp;
    public javax.swing.JPanel jPanelJertsInfo;
    private javax.swing.JPanel jPanelJertsInfoTaula;
    private javax.swing.JPanel jPanelJertsKud;
    public javax.swing.JPanel jPanelKami;
    private javax.swing.JPanel jPanelKamiGorp;
    public javax.swing.JPanel jPanelKamiInfo;
    private javax.swing.JPanel jPanelKamiInfoTaula;
    private javax.swing.JPanel jPanelKamiKud;
    public javax.swing.JPanel jPanelPrak;
    private javax.swing.JPanel jPanelPrakBotoiak;
    private javax.swing.JPanel jPanelPrakBotoiak1;
    private javax.swing.JPanel jPanelPrakGorp;
    public javax.swing.JPanel jPanelPrakInfo;
    private javax.swing.JPanel jPanelPrakInfoTaula;
    private javax.swing.JPanel jPanelPrakKud;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPaneProd;
    public javax.swing.JTable jTableJertsInfo;
    public javax.swing.JTable jTableKamiInfo;
    public javax.swing.JTable jTablePrakInfo;
    private javax.swing.JTextField jTextFieldBilatu2;
    private javax.swing.JTextField jTextFieldBilatu3;
    private javax.swing.JTextField jTextFieldBilatu5;
    public javax.swing.JTextField jTextFieldKodeJerts;
    public javax.swing.JTextField jTextFieldKodeJerts1;
    public javax.swing.JTextField jTextFieldKodeJerts2;
    public javax.swing.JTextField jTextFieldKolorea;
    public javax.swing.JTextField jTextFieldKolorea1;
    public javax.swing.JTextField jTextFieldKolorea2;
    public javax.swing.JTextField jTextFieldLuzeera;
    public javax.swing.JTextField jTextFieldMarka;
    public javax.swing.JTextField jTextFieldMarka1;
    public javax.swing.JTextField jTextFieldMarka2;
    public javax.swing.JTextField jTextFieldPrezioa;
    public javax.swing.JTextField jTextFieldPrezioa1;
    public javax.swing.JTextField jTextFieldPrezioa2;
    public javax.swing.JTextField jTextFieldStock;
    public javax.swing.JTextField jTextFieldStock1;
    public javax.swing.JTextField jTextFieldStock2;
    // End of variables declaration//GEN-END:variables
}
